import type {
  FooterContent,
  HeroContent,
  Plan,
  PlanesContent,
  PortfolioContent,
  PortfolioItem,
  Service,
} from '@/types'

export const SITE_CONFIG = {
  name: '.WAL',
  role: 'Social Media Content Designer',
  description: 'Producción audiovisual y dirección de arte para marcas que quieren liderar.',
  instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL ?? 'https://www.instagram.com',
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_URL ?? 'https://wa.me',
  location: 'San José, Costa Rica',
  locationUrl: 'https://www.google.com/maps/place/San+Jos%C3%A9,+Costa+Rica',
  mapsUrl: 'https://www.google.com/maps/place/San+Jos%C3%A9,+Costa+Rica',
} as const

export const SERVICES: Service[] = [
  { n: '01', label: 'Fotografía', href: '#portafolio' },
  { n: '02', label: 'Video', href: '#portafolio' },
  { n: '03', label: 'Redes Sociales', href: '#portafolio' },
  { n: '04', label: 'Eventos', href: '#planes' },
]

export const HERO_CONTENT: HeroContent = {
  nameLine1: 'WANDERLEY',
  nameLine2: 'ALVARADO L.',
  roleLabel: 'Social media content designer',
  descriptionLead: 'Convirtamos ideas en ',
  descriptionBold: 'contenido visual que conecta, vende y se recuerda.',
  descriptionTail:
    ' Desde campañas conceptuales, identidades completas para marcas que quieren destacar en redes sociales hasta memorias que duran para siempre.',
  primaryCta: { label: 'Iniciar un proyecto', href: SITE_CONFIG.whatsapp, external: true },
  secondaryCta: { label: 'Ver portafolio', href: '#portafolio' },
  scrollLabel: 'DESLIZA',
  portraitSrc: '/images/hero/portrait.jpg',
  portraitAlt: 'Retrato en blanco y negro de Wanderley Alvarado L.',
}

export const PORTFOLIO_CONTENT: PortfolioContent = {
  kicker: 'Portafolio',
  title: 'Trabajo seleccionado',
  description: 'Una selección de piezas en video y fotografía — formato vertical y horizontal.',
  filters: [
    { key: 'todo', label: 'Todo' },
    { key: 'video', label: 'Video' },
    { key: 'foto', label: 'Foto' },
  ],
}

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'item-01',
    n: '01',
    title: 'Marca personal',
    tag: 'Ale Bertarioni',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-01.jpg',
    imageAlt: 'Retrato de moda deportiva en azotea con vista a la ciudad',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-02',
    n: '02',
    title: 'B-roll',
    tag: 'Brandon Solís',
    category: 'video',
    isVideo: true,
    imageSrc: '/images/portfolio/item-02.jpg',
    imageAlt: 'Cuadro de video de reel de lanzamiento de producto',
    videoUrl: 'https://youtube.com/shorts/Hl_31D7a0aM?feature=share',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-03',
    n: '03',
    title: 'Fotografía de producto',
    tag: 'Brauer',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-03.jpg',
    imageAlt: 'Fotografía de producto de reloj de lujo sobre estuche',
    aspectRatio: 'square',
  },
  {
    id: 'item-04',
    n: '04',
    title: 'Bodas',
    tag: 'H&T',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-04.jpg',
    imageAlt: 'Pareja de recién casados saliendo de la ceremonia entre invitados',
    aspectRatio: 'landscape',
  },
  {
    id: 'item-05',
    n: '05',
    title: 'Memorias',
    tag: 'Boda H&T',
    category: 'campaña',
    isVideo: true,
    imageSrc: '/images/portfolio/item-05.jpg',
    imageAlt: 'Cuadro de video de spot de apertura de campaña',
    videoUrl: 'https://youtu.be/QVPiSyamR1I',
    aspectRatio: 'landscape',
  },
  {
    id: 'item-06',
    n: '06',
    title: 'Retratos corporativos',
    tag: 'Marco Pérez',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-06.jpg',
    imageAlt: 'Retrato corporativo en blanco y negro de hombre de traje',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-07',
    n: '07',
    title: 'Reel',
    tag: 'Ale Bertarioni',
    category: 'video',
    isVideo: true,
    imageSrc: '/images/portfolio/item-07.jpg',
    imageAlt: 'Cuadro de video vertical de detalle de producto',
    videoUrl: 'https://youtube.com/shorts/QOH7MHattHE',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-08',
    n: '08',
    title: 'Redes sociales',
    tag: 'El social Sabana',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-08.jpg',
    imageAlt: 'Retrato de mujer con gafas de sol junto a letrero de neón en evento nocturno',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-09',
    n: '09',
    title: 'Foto gastronómica',
    tag: 'Pho restaurante',
    category: 'foto',
    isVideo: false,
    imageSrc: '/images/portfolio/item-09.jpg',
    imageAlt: 'Fotografía de plato gourmet servido en restaurante',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-10',
    n: '10',
    title: 'Recap evento de marca',
    tag: 'Michael Kors',
    category: 'video',
    isVideo: true,
    imageSrc: '/images/portfolio/item-10.jpg',
    imageAlt: 'Cuadro de video vertical detrás de cámaras',
    videoUrl: 'https://youtube.com/shorts/jp-PDDdlarM',
    aspectRatio: 'portrait',
  },
  {
    id: 'item-11',
    n: '11',
    title: 'Hospedajes',
    tag: 'Cabañas Vista Verde',
    category: 'video',
    isVideo: true,
    imageSrc: '/images/portfolio/item-11.jpg',
    imageAlt: 'Cuadro de video vertical de momento destacado',
    videoUrl: 'https://youtube.com/shorts/BlUcC4qhPXU?feature=share',
    aspectRatio: 'portrait',
  },
]

export const PLANES_CONTENT: PlanesContent = {
  kicker: 'Planes',
  title: 'Elegí tu plan',
  description:
    'Si ya tienes un objetivo claro, estos planes están pensados justamente para mejorar tu contenido en redes sociales. Sin embargo, también pienso que cada proyecto merece un presupuesto a su medida — es por eso que conversar es la mejor manera de brindarte una mejor cotización.',
  ctaLabel: 'Conversemos',
  placeholderTitle: 'Arrastra la imagen de este plan',
  placeholderSubtitle: 'o busca en tus archivos',
}

export const PLANS: Plan[] = [
  {
    key: 'referente',
    nav: 'Referente',
    num: '001',
    title: 'Referente',
    lead: 'Para marcas que desean liderar, no solo participar.',
    quote: 'Enfoque en expansión, liderazgo y permanencia en la mente del consumidor.',
    priceNum: '1200',
    imageSrc: '/images/plans/plan-referente.jpg',
    imageAlt: 'Mockup de contenido del Plan Referente',
    features: [
      { icon: 'ic-clapper', text: '2 Producciones mensuales' },
      { icon: 'ic-play', text: '8 Videos optimizados para redes sociales' },
      { icon: 'ic-camera', text: 'Fotografía profesional' },
      { icon: 'ic-image', text: '4 Artes gráficos para redes sociales' },
      {
        icon: 'ic-notion',
        text: 'Su propio sistema de organización de guiones, copys y calendarización de publicaciones',
      },
      { icon: 'ic-mega', text: 'Administración de anuncios Facebook e Instagram Ads' },
    ],
  },
  {
    key: 'posicionamiento',
    nav: 'Posicionamiento',
    num: '002',
    title: 'Posicionamiento',
    lead: 'Contenido con estrategia real detrás.',
    desc: 'Diseñado para marcas personales que buscan construir autoridad y coherencia. Cada pieza cumple una función dentro de un sistema orientado al crecimiento sostenible.',
    quote: 'Enfoque en estructura, consistencia y posicionamiento claro.',
    priceNum: '750',
    imageSrc: '/images/plans/plan-posicionamiento.jpg',
    imageAlt: 'Mockup de contenido del Plan Posicionamiento',
    features: [
      { icon: 'ic-play', text: '4 Videos optimizados para redes sociales' },
      { icon: 'ic-camera', text: 'Fotografía profesional' },
      { icon: 'ic-image', text: '2 Artes gráficos para redes sociales' },
      {
        icon: 'ic-notion',
        text: 'Su propio sistema de organización de guiones, copys y calendarización de publicaciones',
      },
      { icon: 'ic-mega', text: 'Administración de anuncios Facebook e Instagram Ads' },
    ],
  },
  {
    key: 'impulso-estrategico',
    nav: 'Imp. estratégico',
    num: '003',
    title: 'Impulso estratégico',
    lead: 'Para quienes ya dieron el primer paso y quieren avanzar con dirección.',
    desc: 'Este plan combina producción y estructura básica de contenido, permitiendo comenzar a posicionar tu marca con mayor intención y coherencia visual.',
    quote: 'Enfoque en impacto, conversión y resultados a corto plazo.',
    priceNum: '550',
    imageSrc: '/images/plans/plan-impulso-estrategico.jpg',
    imageAlt: 'Mockup de contenido del Plan Impulso Estratégico',
    features: [
      { icon: 'ic-play', text: '3 Videos optimizados para redes sociales' },
      { icon: 'ic-camera', text: 'Fotografía profesional' },
      { icon: 'ic-image', text: 'Arte gráfico para redes sociales' },
    ],
  },
  {
    key: 'fundamentos',
    nav: 'Fundamentos',
    num: '004',
    title: 'Fundamentos',
    lead: 'Todos necesitamos dar ese primer paso.',
    desc: 'Sé lo importante y difícil que puede llegar a ser; por eso este y cada plan está diseñado para marcas que desean comenzar a construir una presencia profesional y coherente.',
    quote: 'Enfoque en claridad, consistencia y primeros pasos con criterio.',
    priceNum: '250',
    imageSrc: '/images/plans/plan-fundamentos.jpg',
    imageAlt: 'Mockup de contenido del Plan Fundamentos',
    features: [
      { icon: 'ic-play', text: '2 Videos optimizados para redes sociales' },
      { icon: 'ic-camera', text: 'Fotografía profesional' },
    ],
  },
]

export const FOOTER_CONTENT: FooterContent = {
  description:
    'Producción audiovisual y dirección de arte para marcas que quieren dejar de participar y empezar a liderar.',
  ctaLabel: 'Iniciar un proyecto',
  navLabel: 'Navegación',
  navLinks: [
    { label: 'Portafolio', href: '#portafolio' },
    { label: 'Planes', href: '#planes' },
    { label: 'Conversemos', href: SITE_CONFIG.whatsapp, external: true },
  ],
  contactLabel: 'Contacto',
  contactItems: [
    { icon: 'instagram', label: 'Instagram', href: SITE_CONFIG.instagram },
    { icon: 'whatsapp', label: 'WhatsApp', href: SITE_CONFIG.whatsapp },
    { icon: 'pin', label: SITE_CONFIG.location, href: SITE_CONFIG.mapsUrl },
  ],
  statusLabel: 'Disponible para nuevos proyectos',
}
